// Generated by CoffeeScript 1.10.0
module.exports = function(funcs, last) {
  var context, i;
  i = 0;
  context = {
    _call: function() {
      return funcs[++i].bind(context);
    },
    _last: function() {
      var a, args;
      args = (function() {
        var j, len, results;
        results = [];
        for (j = 0, len = arguments.length; j < len; j++) {
          a = arguments[j];
          results.push(a);
        }
        return results;
      }).apply(this, arguments);
      args.unshift(null);
      return last.apply(context, args);
    },
    _error: function(err) {
      return last.apply(context, [err]);
    }
  };
  return funcs[0].apply(context);
};
