// Generated by CoffeeScript 1.10.0
module.exports = function(funcs, end) {
  var context, i;
  i = 0;
  context = {
    _then: function() {
      if (i + 1 >= funcs.length) {
        throw new Error('Already in the last function : no more function to call');
      }
      return funcs[++i].bind(context);
    },
    _end: function() {
      var a, args;
      if (!end) {
        throw new Error('No end function defined (second argument)');
      }
      args = (function() {
        var j, len, results;
        results = [];
        for (j = 0, len = arguments.length; j < len; j++) {
          a = arguments[j];
          results.push(a);
        }
        return results;
      }).apply(this, arguments);
      args.unshift(null);
      return end.apply(context, args);
    },
    _error: function(err) {
      if (!end) {
        throw new Error('Cannot transmit error : No end function defined (second argument)');
      }
      if (!err) {
        return;
      }
      return end.apply(context, [err]);
    }
  };
  return funcs[0].apply(context);
};
